### ISSUE TITLE
Thanks so much for this project!

### ISSUE THREAD

**Issue by karlhorky** [arethetypeswrong/arethetypeswrong.github.io#1]
Hi @andrewbranch,

Just wanted to open this issue to say thanks for this! As a user, it's really hard to know if types are correct in all module constellations, and this is a big help.

Thanks again for your continued effort here and also in the ecosystem - I'll close this issue now.

**Comment by andrewbranch** [comment]
Thanks for your work bringing these problems to the attention of library authors! The issues you opened recently were a coincidence of good timing; hope this project helps with that effort.
