### ISSUE TITLE
"Internal resolution error" issue for long file paths

### ISSUE THREAD

**Issue by inakiabt** [arethetypeswrong/arethetypeswrong.github.io#101]
While working on a project, attw CLI started to fail suddenly with an "Internal resolution error" when pushing a new component. The unique aspect of this new component is its relatively long name.

It's worth noting that I suspect this might not be an issue with `attw` itself but rather with TypeScript. I'm creating this issue to investigate, just in case my assumption is incorrect.

It appears that the failure is occurring [here](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/packages/core/src/internal/checks/internalResolutionError.ts#L28) while trying to resolve imports within a specific source file.

Interestingly, I've noticed that if the file path length of the imported file exceeds approximately 82 characters (as far as I can tell), `ts.getResolvedModule` fails to resolve the import. This behavior doesn't make any sense, so I suspect there might be something off in my TypeScript configuration or elsewhere.

To assist with troubleshooting, I've created a repository to reproduce the issue:

https://github.com/inakiabt/ts-issue

**Comment by andrewbranch** [comment]
My bet is this has something to do with the tar packing/unpacking. Have you tried running `npm pack`, then unpacking the tarball and seeing whether the file round trips properly?

**Comment by andrewbranch** [comment]
Yep, you found a bug in my fork of untar.js, which was present in the repo I forked from, and also the repo _that_ forked from. Fixed in the latest patch.
