### ISSUE TITLE
[Proposal] Support for analyzing package.json redirects

### ISSUE THREAD

**Issue by MilanKovacic** [arethetypeswrong/arethetypeswrong.github.io#102]
Hi, thank you for the great tool!
It seems that currently, package.json redirects are not being analyzed. Are there plans to implement this feature?

**Comment by andrewbranch** [comment]
Do you have an example? I’m not sure exactly what you mean, but it sounds related to #46.

**Comment by MilanKovacic** [comment]
I was inserting a folder into the package output with a stub package.json to support node10 resolution strategy (https://github.com/single-spa/single-spa-react/tree/fix/types-and-exports/parcel). It was an error on my part, and it seems to be working now :)
