### ISSUE TITLE
Add a cli / roll this into publint

### ISSUE THREAD

**Issue by jasikpark** [arethetypeswrong/arethetypeswrong.github.io#11]
It would be great to have an easy way to run this against a local package! I could see this being a great integration into @bluwy’s https://github.com/bluwy/publint as an extra error category..

**Comment by bluwy** [comment]
I wouldn't mind having this integrated to publint, but if not I think it's also good to have tools exploring this space side-by-side! I do have _opinions_ on linting dual format dts issues last I chatted with Andrew though 😅

**Comment by jasikpark** [comment]
similar interest: https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/12

**Comment by andrewbranch** [comment]
Making a CLI is planned. Publint is great, but I think there are reasons to make a very TS-focused tool like this separate. When I get around to making some real UI for this site, I was planning to add a link to publint.

**Comment by jasikpark** [comment]
sweet!

**Comment by jasikpark** [comment]
do with this issue what you wish :p
