### ISSUE TITLE
Incorrectly passes `bundler` even if `exports.*.types` is missing

### ISSUE THREAD

**Issue by fregante** [arethetypeswrong/arethetypeswrong.github.io#111]
See https://arethetypeswrong.github.io/?p=css-selector-generator%403.6.4

See https://github.com/fczbkk/css-selector-generator/blob/68902ba94b61ed819eb4847c8cceab1d483d1f1d/package.json#L10-L13

From what I see, `moduleResolution:bundler` and `node16` actually fails if the types are not specified in the `exports` map, but this tool passes them both.

<img width="338" alt="Screenshot" src="https://github.com/arethetypeswrong/arethetypeswrong.github.io/assets/1402241/92d2df64-b52e-4085-9f05-ae1797ba1a14">

I submitted a PR to fix it https://togithub.com/fczbkk/css-selector-generator/pull/577/files

**Comment by andrewbranch** [comment]
These resolutions are working correctly (both in tsc and in this tool) via [file extension substitution](https://www.typescriptlang.org/docs/handbook/modules/reference.html#file-extension-substitution). The `import` condition specifies `./esm/index.js`, so TypeScript will successfully find `./esm/index.d.ts`.

**Comment by fregante** [comment]
Uhm, that's not what I'm seeing. 

CI results: can't find the types

https://github.com/pixiebrix/pixiebrix-extension/actions/runs/6650563402/job/18070905027#step:5:1

The error message is very clear:

> error TS7016: Could not find a declaration file for module 'css-selector-generator'. '/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/css-selector-generator/build/index.js' implicitly has an 'any' type.
>  There are types at '/home/runner/work/pixiebrix-extension/pixiebrix-extension/node_modules/css-selector-generator/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'css-selector-generator' library may need to update its package.json or typings.


This is the tsconfig: it worked when the resolution was just `node` but not on `bundler`

https://github.com/pixiebrix/pixiebrix-extension/blob/a2b04ba31401e122a141138478021fa400b7b817/tsconfig.json#L8

The module can only be correctly imported by TypeScript after making the `exports` suggested in  the linked PR.

**Comment by fregante** [comment]
Oh, I see the issue actually. You say:

> The import condition specifies ./esm/index.js, so TypeScript will successfully find ./esm/index.d.ts.

But there's no such `./esm/index.d.ts` file. The types are in a different directory.

**Comment by fregante** [comment]
@andrewbranch if you're interested in resolving this I can work on a repro

**Comment by andrewbranch** [comment]
All the files where the error appears are CJS files, so the errors you’re seeing correspond to the `node16 (from CJS): ❌ No types` row.

**Comment by andrewbranch** [comment]
Oh wait, but your moduleResolution is set to `bundler` there? Something weird is going on. But it’s definitely something in your project, not this tool—the results from the tool match what I see looking at the source code. The results in CI are surprising. Try adding `--traceResolution` to the `tsc` invocation?
