### ISSUE TITLE
TS 5.3 incompatibility

### ISSUE THREAD

**Issue by ghoullier** [arethetypeswrong/arethetypeswrong.github.io#117]
Latest version "@arethetypeswrong/cli": "0.13.1" is not compatible with TS5.3

```console
error while checking file:
ts.getResolvedModule is not a function
```

https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/packages/core/src/internal/checks/internalResolutionError.ts#L28

EDIT: I [forked](https://github.com/ghoullier/arethetypeswrong.github.io/commit/fcf7b128bb0b56f8fa7adce33e6a33584b095545) the project to bump `typescript` and `ts-expose-internals` to 5.3.2 and it also [fails](https://github.com/ghoullier/arethetypeswrong.github.io/actions/runs/6949725632/job/18908422118)

**Comment by markerikson** [comment]
I'm seeing pretty weird behavior on this myself.

Even if I manually run older versions locally, like `npx @arethetypeswrong/cli@0.10.0 ./package.tgz --format table --ignore-rules false-cjs`, I'm still seeing the same error, even though this is the version report:

```
$ attw --version
cli: v0.1.0
core: v0.1.0
typescript: v5.1.3
```

**Comment by myl7** [comment]
Related microsoft/rushstack#4404

It seems that although it is a minor update, TS removes the API.
Though it then added an equivalent API, an easy and fast fix is to limit (override should also work) the TS version as `^5.2.2,<5.3.0`.

**Comment by andrewbranch** [comment]
I was under the impression I had the typescript dependency version pinned in core so I could use internal APIs safely, but I think I messed that up last time I bumped it. Will have a fix out soon.
