### ISSUE TITLE
Update MissingExportEquals.md for import default = fetch

### ISSUE THREAD

**Issue by benasher44** [arethetypeswrong/arethetypeswrong.github.io#130]
It seems that in the case where `export default fetch` and `fetch` refers to a namespace and something else being merged with that namespace, one has to add something like this to the namespace:

```ts
import _default = fetch;
export { _default as default };
```

whereas today, the recommendation is:

```ts
const _default = typeof fetch;
export { _default as default };
```

It would be great to update MissingExportEquals.md to cover this namespace edge case.

**Comment by andrewbranch** [comment]
Let’s see if anything blows up after the @types/node-fetch merge 😄 If nobody complains after a couple days, I agree.

**Comment by andrewbranch** [comment]
@benasher44 would you want to open a PR?

**Comment by benasher44** [comment]
I'm somewhat interested, but I won't have time for the next 4-6 weeks, most likely.
