### ISSUE TITLE
lodash types are wrong (or lying?)

### ISSUE THREAD

**Issue by benasher44** [arethetypeswrong/arethetypeswrong.github.io#131]
I'm not sure 100% what's going on (lodash's js style of exporting is not written in the most standard way — somewhat difficult to parse out in my head), but attw claims lodash's types are correct.

<img width="680" alt="image" src="https://github.com/arethetypeswrong/arethetypeswrong.github.io/assets/1120429/1c1540a4-0c6d-4b01-89ad-02dac9f13fef">

However, named lodash imports fail at runtime in node ESM. For example:

```ts
import { random } from "lodash";
```

This will fail with:

```
SyntaxError: The requested module 'lodash' does not provide an export named 'random'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.10.0
```

**Comment by benasher44** [comment]
Maybe the issue is that the types are correct, but they're lying? If that's the case, feel free to close.

**Comment by benasher44** [comment]
I should add that they only fail when running node on ESM output. This import works fine with CJS import (only tested CJS using module set to node, not nodenext)

**Comment by benasher44** [comment]
Here's a simple program that illustrates the issue:

```ts
import _, { random } from "lodash";
console.log(_.random());
console.log(random());
```

This compiles fine with `tsc --module NodeNext file.ts`, but the import fails at runtime.

**Comment by benasher44** [comment]
Okay so I think I just stumbled upon microsoft/TypeScript#54018. Would it be reasonable to use cjs-module-lexer in this package, and then flag the types with 👺 ?

**Comment by andrewbranch** [comment]
Duplicate of #35? 😉

**Comment by benasher44** [comment]
Oh wow nice!
