### ISSUE TITLE
Conditional exports syntax

### ISSUE THREAD

**Issue by barnjamin** [arethetypeswrong/arethetypeswrong.github.io#165]
Something I just [encountered](https://github.com/wormhole-foundation/wormhole-sdk-ts/pull/416) was a strict interpretation of the `exports` package field syntax such that the resolver aborted with the message

```Module not found: Default condition should be last one```

Indeed it is [documented](https://nodejs.org/api/packages.html#conditional-exports) that it _should_ come last 

> "default" - the generic fallback that always matches. Can be a CommonJS or ES module file. _This condition should always come last._

I'm not sure this falls into the category of bugs this project aims to detect but if so, it seems like a nice one to warn folks about.

**Comment by andrewbranch** [comment]
Interesting. I feel like that might be a better fit for https://publint.dev (which may already include that check)
