### ISSUE TITLE
Proposal: support publishConfig

### ISSUE THREAD

**Issue by waldronmatt** [arethetypeswrong/arethetypeswrong.github.io#172]
First I want to say thank you for this tool, it has been extremely helpful to ensure type compliance on packages.

I've recently adopted a technique in my monorepo where I use my package `exports` to point to source `ts` files so VS Code will reflect "live" types even across package boundaries. I use `publishConfig` to point to `esm` / `cjs`  bundles which overrides `exports` during the packing and publishing process to npm. This technique has been popularized by colinhacks (Zod author): https://colinhacks.com/essays/live-types-typescript-monorepo

It would be amazing if the cli could support parsing through `publishConfig` exports.

**Comment by timostamm** [comment]
TIL about [publishConfig](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#publishconfig):

> This is a set of config values that will be used at publish-time. 

Unfortunately, it appears that the config values are really only applied when you run `npm publish`. They are ignored when you run `npm pack`.

**Comment by andrewbranch** [comment]
I was leaning towards no, and then...

> EDIT: A previous version of this post recommended publishConfig, operating under the mistaken belief that it could be used to override "exports" during npm publish. As it turns out, npm only uses "publishConfig" to override certain .npmrc fields like registry and tag, whereas pnpm has expanded its use to override package metadata like "main", "types", and "exports". There are a number of reasons you may not wish to strongly couple your deployment logic to pnpm (detailed in the publishConfig section below). My updated recommendation is to use a custom export condition plus customConditions in tsconfig.json.

So, yeah. Yikes.

**Comment by zirkelc** [comment]
In case someone needs this, here's a npm script for this:

```json
{
  "scripts": {
    "check-types": "pnpm pack | tail -n1 | xargs attw"
  }
}
```

EDIT:
This deletes the archive afterwards:

```json
{
  "scripts": {
    "check-types": "TARBALL=$(pnpm pack | tail -n1) && attw $TARBALL && rm -f $TARBALL"
  }
}
```

**Comment by StyleShit** [comment]
> I was leaning towards no, and then...
> 
> > EDIT: A previous version of this post recommended publishConfig, operating under the mistaken belief that it could be used to override "exports" during npm publish. As it turns out, npm only uses "publishConfig" to override certain .npmrc fields like registry and tag, whereas pnpm has expanded its use to override package metadata like "main", "types", and "exports". There are a number of reasons you may not wish to strongly couple your deployment logic to pnpm (detailed in the publishConfig section below). My updated recommendation is to use a custom export condition plus customConditions in tsconfig.json.
> 
> So, yeah. Yikes.

Sorry for commenting on a closed issue, but it does work as intended in pnpm.

Maybe we could somehow provide (or automatically infer?) the package manager and use that when packing the package instead of a hard-coded `npm pack`:

https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/161725ad2e8957f109e44fb26b13c9d70f415c2f/packages/cli/src/index.ts#L201

wdyt?
