### ISSUE TITLE
[Feature] Adding JUnit XML to the output.

### ISSUE THREAD

**Issue by Morgul** [arethetypeswrong/arethetypeswrong.github.io#187]
So, I would like to add `attw` it part of my CI/CD, both for some public projects and some internal ones.

We use GitLab, and GitLab's CI/CD has a cool feature where if you spit out a JUnit xml file, it can display that as a nice GUI, with a full report of the CI/CD run, without it having to know anything about the task itself. I use this often for mocha tests and eslint, and it's great.

* Docs: https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html

Would there be any appetite for me adding it here as another formatter (presumably based on the json formatter)? It would be very handy, I think, as I'm trying to sell more people on checking their exported types and module formats in this crazy dual cjs/esm world.

**Comment by andrewbranch** [comment]
Hey! Sorry for the late reply. I think it would probably best to make this feature as a separate package and run like `attw --format json | attw-junit`. I’m not sure there would be any particularly advantage to developing it as a built-in format.

**Comment by Morgul** [comment]
That's fair. (And something I considered, but then moved on to other projects at work.) If I go back and build one, I'll link it here.
