### ISSUE TITLE
`lru-cache` dependency breaks the declared Node.js compatibility

### ISSUE THREAD

**Issue by RobinTail** [arethetypeswrong/arethetypeswrong.github.io#204]
Adding this line:

https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/8632156c9eabf484623d974d5259bb847ea473c8/packages/core/package.json#L56

Broke the Node.js compatibility of the package.

```
error lru-cache@11.0.1: The engine "node" is incompatible with this module. Expected version "20 || >=22". Got "18.18.0"
```

Commit: 33abbdb128985cc10601acb51dbcbe655e39e8d1

The package Node.js compatibility is declared as `>= 18`, but that dependency is not compatible with v18.

CC @andrewbranch

**Comment by RobinTail** [comment]
Suggesting to use `lru-cache` v10, since it was only v11 that recently dropped Node 18 according to the changelog:
https://github.com/isaacs/node-lru-cache/blob/main/CHANGELOG.md

**Comment by andrewbranch** [comment]
I think I’ll probably drop support for v18 myself. I feel like supporting only active LTS versions is fine for a CI tool.

**Comment by RobinTail** [comment]
Node 18.18+ is LTS at the moment, @andrewbranch 

![image](https://github.com/user-attachments/assets/d63ede96-6b9d-4b92-ab06-1e9a9cd9f736)

**Comment by RobinTail** [comment]
Dear @andrewbranch ,

you're making a very important tool for the community and I believe you can drop Node 18 in May 2025, but at the moment it needs a little care: please review my PR, it works fine with previous version of `lru-cache`.

https://github.com/arethetypeswrong/arethetypeswrong.github.io/pull/205

**Comment by RobinTail** [comment]
The workaround for `yarn`

```json lines
  "resolutions": {
    "@arethetypeswrong/**/lru-cache": "^10"
  },
```
