### ISSUE TITLE
Named exports: false positive with compiled `export * from` syntax?

### ISSUE THREAD

**Issue by haines** [arethetypeswrong/arethetypeswrong.github.io#208]
I think we're getting a false positive from the named ESM exports problem detection.

For [@cerbos/core](https://www.npmjs.com/package/@cerbos/core), we get a missing named exports problem for nearly everything exported from the package entrypoint.

The allegedly-missing exports are defined using `export * from "./wherever"` syntax so `tsc` produces JS like 

```js
__exportStar(require("./wherever"), exports);
```

which does seem like it might not be statically analyzable, but it works in practice.

Given this `package.json`

```json
{
  "type": "module",
  "private": true,
  "dependencies": {
    "@cerbos/core": "^0.18.1"
  }
}
```

and this `index.mjs`

```js
import { Client } from "@cerbos/core";

console.log(Client);
```

then Node.js (v20.17.0, at least) is able to resolve the named import of `Client`:

```console
$ node index.mjs
[class Client]
```

but `attw` reports problems from the "node16 (from ESM)" check, with `Client` (among others) listed as missing:

```console
$ npx --yes @arethetypeswrong/cli --format json --from-npm @cerbos/core
{
  ...,
  "problems": {
    "NamedExports": [
      {
        "kind": "NamedExports",
        "implementationFileName": "/node_modules/@cerbos/core/lib/index.js",
        "typesFileName": "/node_modules/@cerbos/core/lib/index.d.ts",
        "isMissingAllNamed": false,
        "missing": [
          "_addInstrumenter",
          "_removeInstrumenter",
          "_AbortHandler",
          "Client",
          ...
        ]
      }
    ]
  }
}
```

[Full output](https://github.com/user-attachments/files/17010459/output.json)

The weird thing is that I've tried creating [a minimal reproduction on StackBlitz](https://stackblitz.com/edit/stackblitz-starters-kttq9r?file=package.json) and it doesn't report any problems.

**Comment by andrewbranch** [comment]
Thanks for the report!
