### ISSUE TITLE
Suggest removing unnecessary `types` conditions

### ISSUE THREAD

**Issue by emmatown** [arethetypeswrong/arethetypeswrong.github.io#25]
For packages like this:

```ts
{
  "name": "pkg",
  "exports": {
    "types": "./dist/index.d.ts",
    "default": "./dist/index.js"
  }
}
```

It might be nice to say that the `types` condition here is unnecessary and suggest removing it.

**Comment by andrewbranch** [comment]
I think this is probably too opinionated for this tool.
