### ISSUE TITLE
Can I ignore an entry in exports?

### ISSUE THREAD

**Issue by NullVoxPopuli** [arethetypeswrong/arethetypeswrong.github.io#30]
my packages have a legacy/support entrypoint, which isn't exactly public API, but is there for folks who know about.

It's also a CJS module, but with an ambiguous entry in the exports.
I'd like to ignore checking this file / exports, because it ultimately wouldn't be used by 99.999% of users.

Is this possible? possible soon? thanks!!

**Comment by andrewbranch** [comment]
Yes 😄

**Comment by gabro** [comment]
I also have a similar scenario, but for `.css` files that my component library exposes.

Does it make sense to exclude them? Or would it be better to provide a `.d.ts` for those .css files?

**Comment by andrewbranch** [comment]
It probably makes more sense to exclude them.

**Comment by RobbieTheWagner** [comment]
How can we exclude CSS files then?

**Comment by Kenneth-Sills** [comment]
@RobbieTheWagner Looks like this'd be done over with the CLI's  [`--exclude-entrypoints`](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/3729bc2a3ca2ef7dda5c22fef81f89e1abe5dacf/packages/cli/README.md#entrypoints) argument, which can also be pre-specified in the `.attw.json` file.
