### ISSUE TITLE
Duplicated InternalResolutionError

### ISSUE THREAD

**Issue by andrewbranch** [arethetypeswrong/arethetypeswrong.github.io#36]
At https://arethetypeswrong.github.io/?p=%40ice%2Fapp%403.2.6, `problems[4]` and `problems[6]` appear to be identical.

**Comment by userquin** [comment]
Why is this failing (vite-plugin-pwa)?

![imagen](https://github.com/arethetypeswrong/arethetypeswrong.github.io/assets/6311119/7c6e66f3-7ccc-470a-9ae9-b73e75b882c3)

**Comment by andrewbranch** [comment]
Vite has a lot of this problem https://github.com/vitejs/vite/issues/11552

**Comment by userquin** [comment]
I mean in the website here, a few weeks ago, checking `vite-plugin-pwa` using the site was working https://arethetypeswrong.github.io/?p=vite-plugin-pwa%400.16.4, with latest changes in the web in this repo it is failing.

**Comment by andrewbranch** [comment]
InternalResolutionError was just added in #31 to fix #22. This tool is still under development and is learning to detect more kinds of problems 🙂
