### ISSUE TITLE
Clarity on "Masquerading as CJS"

### ISSUE THREAD

**Issue by benasher44** [arethetypeswrong/arethetypeswrong.github.io#37]
Discussing in https://github.com/sequelize/sequelize/issues/16157#issuecomment-1600960433. I think it means that the index.d.ts is the same one used for CJS, but it's more of a warning, since it'll work as long as there is no ESM-incompatible syntax?

**Comment by andrewbranch** [comment]
Nearly perfect timing! I’m working on full explainers for each problem. They’re not done, but that one is already committed to the WIP branch: https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/docs/docs/problems/FalseCJS.md

Let me know if that clears things up.

**Comment by benasher44** [comment]
I think that helps me! I'll post this in the other ticket.

**Comment by andrewbranch** [comment]
That would be great. Make sure you read all the bad consequences of it before you go set other projects up to ignore it too though 😉

**Comment by andrewbranch** [comment]
@benasher44 that link is in `main` now. You may want to update your link in the other thread in case I absentmindedly delete the `docs` branch (which I’d prefer to do since it’s a merged feature branch now).
