### ISSUE TITLE
Allow additional entrypoints to be specified

### ISSUE THREAD

**Issue by andrewbranch** [arethetypeswrong/arethetypeswrong.github.io#40]
When a package doesn’t have package.json `exports` or exposes a wildcard in its `exports`, it would be nice to allow the user to manually specify an entrypoint to check. On the website, this could be done interactively; in the CLI, a new option will be needed. This would effectively eliminate the “Wildcard subpaths cannot yet be analyzed by this tool” problem kind.

**Comment by NullVoxPopuli** [comment]
What if, for wildcards, we use globby to detect what js files exist that match those globs, and then check to see if there are correspending d.ts files, resolveable via exports.types or typesVersions or whatever?

**Comment by andrewbranch** [comment]
Yeah, there’s some logic in TS Server like this for path completions. Could be a good option.
