### ISSUE TITLE
feat: add `@webcontainer/api` file system support

### ISSUE THREAD

**Issue by userquin** [arethetypeswrong/arethetypeswrong.github.io#48]
is there any chance to add [@webcontainer/api file system](https://webcontainers.io/guides/working-with-the-file-system#file-system-operations-fs`) filesystem support in core package?

I want to use the core here to configure monaco editor reading tsconfig file or vanillajs with some provided defaults (from local project). I need the resolution implementation to provide the libraries to the editor via [addExtraLib](https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.LanguageServiceDefaults.html) call.

**Comment by userquin** [comment]
Screenshot of the app running Vite dev server with custom plugin: the custom plugin will load a small IDE with the project itself (with monaco editor to allow fs operations):

![imagen](https://github.com/arethetypeswrong/arethetypeswrong.github.io/assets/6311119/599bc654-884e-487e-b936-427b007bc2a9)

**Comment by andrewbranch** [comment]
You can provide your own file system host to this tool, but it sounds like you should be doing that directly with TypeScript APIs, not arethetypeswrong.
